name: tanguangyun/TanChat:latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: tanguangyun/TanChat:latest
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
